### ISSUE TITLE
catch error in promise answer: (error http 429)

### ISSUE THREAD

**Issue by MatthewZMD** [thanhvg/emacs-howdoyou#10]
Fresh install of howdoyou from melpa, config:
```
(use-package howdoyou
  :defer t
  :commands (howdoyou-query))
```

I am getting the error `catch error in promise answer: (error http 429)` when I try to search any query. Any clues?

**Comment by thanhvg** [comment]
What os you are on? I can't tell for Windows, but if you on Linux or Mac make sure you have curl installed as the built in url.el is problematic. 

It may has nothing to do with this error but I don't think you need to set :commands (howdoyou-query). It and other commands are autoloaded already.

**Comment by MatthewZMD** [comment]
I'm on Linux, and yes curl has been setup

**Comment by thanhvg** [comment]
Then try to run query straight from curl. First with Google:
```
curl -A "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0" https://www.google.com/search?q=howdoy%20you%20re%20site%3Astackoverflow.com%20OR%20site%3Astackexchange.com%20OR%20site%3Asuperuser.com%20OR%20site%3Aserverfault.com%20OR%20site%3Aaskubunu.com

```
Then with a stackoverlow link. See if curl throws the 429 error. 
You can post curl results here I'll take a look when I have time.

**Comment by MatthewZMD** [comment]
This morning I tried your curl, works fine. Then I tried a curl with stackoverflow, working fine as well. And it's also working perfectly fine in howdoyou too! 

Not sure what changed, but I should close this issue now.
