### ISSUE TITLE
Switch to *How Do You* buffer after search

### ISSUE THREAD

**Issue by leothelocust** [thanhvg/emacs-howdoyou#3]
First I'd like to say awesome work! I love this tool already, and I've only been using it for half a day.

I have a feature suggestion.  First, is it possible to "goto" the *How Do You* buffer after the search is complete and the Org window and buffer is open?  I'm not that skilled in emacs lisp or I would attempt to just create my own function to achieve this.

Something like:
```lisp
(defun howdoyou-query-and-follow ()
    "After performing search, automagically go to the new buffer."
    (interactive)
    (howdoyou-query)
    (other-window))
```

Obviously this doesn't work, the search is done as a promise and in this case `other-window` is called before the query is entered or performed.

Anyway, please let me know if there is a simple way to get what I'm after.  Again, GREAT work! Love this tool!

**Comment by thanhvg** [comment]
I will add an option to follow the buffer. Several commits ago it was the default behavior but then I changed my mind :)

Thanks for the PR and the suggestion.
